config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'likes/index'

  devise_for :users
  resources :users, only: [:show]
    get 'welcome/index'
  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :likes, only: [:index, :create, :destroy]
    end
  end

  root to: 'welcome#index'
  post '/incoming', to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :likes, dependent: :destroy
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :topics, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_bookmarks, through: :likes, source: :bookmark

  def liked(bookmark)
    likes.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmark = Bookmark.all
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.topic = @topic
    @bookmark.user = current_user
    if @bookmark.save
      flash[:notice]= "The bookmark was saved."
      redirect_to [@topic, @bookmark]
    else
      flash.now[:error]= "The bookmark was not saved. Please try again."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.save
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark
    if @bookmark.save
      flash[:notice]= "The bookmark was updated."
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:error]= "The bookmark was not updated. Please try again."
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    authorize @bookmark
    if @bookmark.destroy
      flash[:notice]= "\"#{@bookmark.name}\" was deleted successfully."
      redirect_to @bookmark.topic
    else
      flash[:error]= "There was an error in deleting the bookmark."
      render :show
    end
  end


  def bookmark_params
    params.require(:bookmark).permit(:url, :name)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!, only: [:create]

  def create
    title = params[:subject]
    email = params[:sender]
    @user = User.find_by(email: email)

    if @user.nil?
      @user = User.create!(email: email, password: 'password')
      @user.skip_confirmation!
      @user.save!
    end

   @topic = Topic.find_by(title: title, user: @user) || Topic.create!(title: title, user: @user)
    @url = params['body-plain']




    Bookmark.create!(topic: @topic, user: @user, url: @url)
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]

    # Check if user is nil, if so, create and save a new user

    # Check if the topic is nil, if so, create and save a new topic

    # Now that you're sure you have a valid user and topic, build and save a new bookmark

    # Assuming all went well.
    head 200
  end


end

app/controllers/incoming_controller_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_action :authenticate_user!, only: [:create]

  def create
    title = params[:subject]
    email = params[:sender]
    @user = User.find_by(email: email)

    if @user.nil?
      @user = User.create!(email: email, password: 'password')
      @user.skip_confirmation!
      @user.save!
    end

   @topic = Topic.find_by(title: title, user: @user) || Topic.create!(title: title, user: @user)
    @url = params['body-plain']




    Bookmark.create!(topic: @topic, user: @user, url: @url)
    # Find the user by using params[:sender]
    # Find the topic by using params[:subject]
    # Assign the url to a variable after retreiving it from params["body-plain"]

    # Check if user is nil, if so, create and save a new user

    # Check if the topic is nil, if so, create and save a new topic

    # Now that you're sure you have a valid user and topic, build and save a new bookmark

    # Assuming all went well.
    head 200
  end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    respond_with({:msg => "success"})
  end

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark_id: @bookmark.id)

    if like.save
      flash[:success] = "You like this bookmark!"
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "Something went wrong. Let's try that again."
      redirect_to [@bookmark.topic, @bookmark]
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = @bookmark.likes.where(user_id: current_user.id).first

    if like.destroy
      flash[:success] = "You unliked this bookmark."
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:alert] = "Something went wrong. Let's try that again."
      redirect_to [@bookmark.topic, @bookmark]
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
    @topic
  end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      flash[:notice]= "Topic was saved."
      redirect_to @topic
    else
      flash.now[:alert]= "The topic could not be saved. Please try again"
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    @topic.save!
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(topic_params)

    if @topic.save
      flash[:notice]= "The topic was saved sucessfully."
      redirect_to @topic
    else
      flash.now[:alert]= "There was an error saving the topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    if @topic.destroy
      flash[:notice]= "\"#{@topic.title}\" was deleted successfully."
      redirect_to topics_path
    else
      flash.now[:alert] = "There was an error in deleting this topic."
      render :show
    end
  end

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
     @user = User.find(params[:id])
     @user_bookmarks = @user.bookmarks
     @liked_bookmarks = @user.liked_bookmarks
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_controller_helper.rb
module IncomingControllerHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [topic, bookmark] do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "What do you want to call this bookmark?" %>
      </div>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.url_field :url, class: 'form-control', placeholder: "Enter Bookmark URL" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark</h1>
<%= render partial: 'form', locals: { topic: @bookmark.topic, bookmark: @bookmark} %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
<%= render partial: 'form', locals: { topic: @topic, bookmark: @bookmark} %>

app/views/bookmarks/show.html.erb
<h1><a href="<%= @bookmark.url %>"><%= @bookmark.name %></a></h1>
<img src="http://icons.better-idea.org/icon?url=<%= @bookmark.url %>&size=120">
<div class="row">
    <% if policy(@bookmark).update? %>
      <%= link_to "Edit", edit_topic_bookmark_path(@bookmark.topic, @bookmark), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@bookmark).destroy? %>
      <%= link_to "Delete Bookmark", [@bookmark.topic, @bookmark], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this bookmark?"} %>
    <% end %>
  </div>
  <div class="col-md-2">
    <%= render partial: 'likes/like', locals: {bookmark: @bookmark} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmarks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="navbar">
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", welcome_index_path %></li>
    <li><%= link_to "Topics", topics_path %></li>
    <% if user_signed_in? %>
        <li><%= link_to "My Blocmarks", user_path(current_user) %></li>
        <li class="pull-right">Signed in as: <%= current_user.email %></li>
        <li class="pull-right"><%= link_to 'Edit profile', edit_user_registration_path %></li>
        <li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      </ul>
      <ul class="nav pull-right">
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
  </ul>
    </div>

  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
  <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
  <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/likes/_like.html.erb
<% if policy(Like.new).create? %>
  <div>
    <% if like = current_user.liked(bookmark) %>
      <%= link_to [bookmark.topic, bookmark, like], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty" > </i>&nbsp; Unlike
      <% end %>
    <% else %>
      <%= link_to [bookmark.topic, bookmark, Like.new], class: 'btn btn-primary', method: :post do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Like
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [topic] do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic name" %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
<%= render partial: 'form', locals: { topic: @topic, post: @post} %>

app/views/topics/index.html.erb
<h1>All Topics</h1>
<% if current_user %>
    <div class="container-fluid">
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    </div>
    <br>
<% end %>

<% @topics.each do |topic| %>
  <div class="container-fluid">
    <div class="media">
      <a class="media-left" href="#">
        <span class="glyphicon glyphicon-book"></span>
      </a>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to topic.title, topic %></h4>

      </div>
    </div>
  </div>

<% end %>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render partial: 'form', locals: {topic: @topic} %>

app/views/topics/show.html.erb
<center><h1><%= @topic.title %></h1></center>
<div class="row">
  <div class="col-md-8">
    <%= link_to "Edit Topic", edit_topic_path(@topic), class: 'btn btn-success' %> <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger' %></center>
  <br>
  <%= link_to "Add new bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
  <br>
  <div class="row">
    <div class="col-md-8">
      <% @bookmarks.each do |bookmark| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">

              <span class="glyphicon glyphicon-bookmark"></span>


              <%= render partial: 'likes/like', locals: { bookmark: bookmark } %>
              <% if policy(bookmark).update? %>
              <%= link_to bookmark.url, bookmark.url, :target => '_blank' %>
                <%= link_to "Edit Bookmark", edit_topic_bookmark_path(@topic, bookmark), class: 'btn btn-success' %>
              <% end %>
              <%= link_to "Delete Bookmark", topic_bookmark_path(@topic, bookmark), method: :delete, class: 'btn btn-danger' %>
            </h4>
          </div>
        </div>
      </div>
    </div>
      <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="row">
  <h2>Your Bookmarks:</h2>
  <br>
    <div class="col-md-8">
      <% @user_bookmarks.each do |bookmark| %>
          <h4 class="media-heading">
            <%="##{bookmark.topic.title}" %>
            <br>
            <%= link_to bookmark.url, bookmark.url, :target => '_blank' %> <%= link_to "Delete", [bookmark.topic, bookmark], method: :delete, class: 'btn btn-danger' %>
            <br>
          </h4>
      <% end %>
    </div>
</div>
    <br>
<div class="row">
  <h3>Liked Bookmarks:</h3>
  <br>
      <div class="col-md-8">
        <% @liked_bookmarks.each do |bookmark| %>
          <h4 class="media-heading">
              <%="##{bookmark.topic.title}" %>
              <br>
              <%= link_to bookmark.url, bookmark.url, :target => '_blank' %> <%= render partial: "likes/like", locals: { bookmark: bookmark } %>
              <br>
          </h4>
        <% end %>
    </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmarks</h1>
<p>Bookmarks with Bloc</p>